name: Update Cloudflared Version
on:
  repository_dispatch:
  workflow_dispatch:  
  schedule:
    - cron:  '0 0 * * *'
  
jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set environment variables
      run: |
        echo "::set-env name=TOKEN::${{ secrets.GITHUB_TOKEN }}"

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install requests

    - name: Update Version
      run: |
        # Get the latest version number from cloudflared's release page
        latest_version=$(curl --silent https://api.github.com/repos/cloudflare/cloudflared/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')

        # Update the PKG_VERSION variable in the Makefile
        sed -i "s/PKG_VERSION:=.*/PKG_VERSION:=$latest_version/" ./openwrt-cloudflared/Makefile

        # Increment the PKG_RELEASE variable
        release_number=$(grep 'PKG_RELEASE:=' ./openwrt-cloudflared/Makefile | awk -F '=' '{print $2}')
        release_number=$((release_number + 1))
        sed -i "s/PKG_RELEASE:=.*/PKG_RELEASE:=$release_number/" ./openwrt-cloudflared/Makefile
